### PR TITLE
Fixed conflict between SVG images and fonts

### PR DESCRIPTION
**Pull request by kuatro**

### CODE REVIEW

**Comment by TriPSs** [comment]
If i understand this correct, the webpack image compiler also compiles the svg images that are fonts? If this is the case then i think we need to exclude the fonts from the image compiler.

**Comment by kuatro** [comment]
@TriPSs Webpack didn't compile the SVG images at all.

**Comment by TriPSs** [comment]
@kuatro That's wierd, i checked and if i imported a SVG image it got compiled bij the image compiler.

Could you clarify this for me?

**Comment by kuatro** [comment]
@TriPSs Sorry, forgot to describe, the problem happens when you use SVG images in CSS (i.e. `background-image` property).

**Comment by TriPSs** [comment]
@kuatro Aa, yes is a problem i know. The reason i placed the duck image in `styles/assets` is so you could import the image in a component like 'styles/assets/Duck.jpg` and use the same image in you styles like `assets/Duck.jpg`.

This is because the import of styles start in the styles directory.

Could you try this?

**Comment by kuatro** [comment]
@TriPSs Yep, that works good with jpg/png/gif, but the problem with SVG is still present. Could you take a look at my simple [demo](https://github.com/kuatro/react-esc-example/tree/demo/svg-images)?
If you'll try to access the SVG file, you'll get a blank file.

**Comment by TriPSs** [comment]
@kuatro Thanks, i see what you meen now. But if i apply you change to the webpack config it does not make any difference.

I think it will also make more sens if we only have 1 compiler/load for the svg, so how do you feel about removing 
```
{
    test: /\.svg(\?.*)?$/,
    loader: 'url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=image/svg+xml'
}
```

I checked it with your demo and the icon got loaded after i deleted this part from the config.

**Comment by kuatro** [comment]
@TriPSs Yes, removing this part also works for me. I just wasn't sure if it's a good approach because maybe someone prefers to use SVG fonts. Should I update this PR with your approach?

**Comment by TriPSs** [comment]
@kuatro Yes that's what I thought ;) 

If you could update your pr i will merge it.

**Comment by TriPSs** [comment]
@kuatro Thanks for the PR!

**Comment by TriPSs** [comment]
[v1.5.0](https://github.com/TriPSs/react-esc/releases/tag/v1.5.0)

**Pull request merged**
